kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

workspace:
  path: /workdir

steps:
- name: build_and_test_image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - apk add curl bash wget tar
  - /usr/local/bin/wait
  - ./ci-build.sh
  - docker build -t ngx:latest .
  - docker tag ngx:latest docker-nginx-proxy:latest
  # environment:
  #   GEOIP_ACCOUNT_ID:
  #     from_secret: geoip_account_id
  #   GEOIP_LICENSE_KEY:
  #     from_secret: geoip_license_key
  when:
    event:
    - pull_request
    - push
    - tag

- name: trivy_scan
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  pull: always
  environment:
    IMAGE_NAME: nginx:latest
    LOCAL_IMAGE: true
    ALLOW_CVE_LIST_FILE: whitelist
    SEVERITY: HIGH,CRITICAL
    # Prevent build failure due to self-signed cert private key detection.
    # This is a non-production key generated at build time for testing.
    FAIL_ON_DETECTION: false
  when:
    event:
    - push
    - pull_request
  depends_on:
    - build_and_test_image

- name: push_image_to_artifactory
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" "$${DOCKER_REPO}"
  - ./publish.sh "ngx" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
  environment:
    DOCKER_BASEDIR: /
    DOCKER_IMAGE: nginx-proxy
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_REPO: artifactory-internal.digital.homeoffice.gov.uk
    DOCKER_USERNAME: docker-nginx-proxy-robot
  depends_on:
    - trivy_scan
  when:
    event:
    - tag

- name: push_image_to_quay
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_QUAY_PASSWORD}" "$${DOCKER_REPO}"
  - ./publish.sh "ngx" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
  environment:
    DOCKER_BASEDIR: /ukhomeofficedigital/
    DOCKER_IMAGE: nginx-proxy
    DOCKER_QUAY_PASSWORD:
      from_secret: docker_quay_password
    DOCKER_REPO: quay.io
    DOCKER_USERNAME: ukhomeofficedigital+nginx_proxy
  depends_on:
    - trivy_scan
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
